variables:
  PORTAINER_MEDIA_SERVER_UPDATE: "https://portainer.serek.io/api/stacks/webhooks/c14e1a79-7248-4b02-8caf-a781b58ceeac"

Update media server:
  script: 
    - apt update
    - apt install -y curl
    - curl -X POST $PORTAINER_MEDIA_SERVER_UPDATE
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - media_server.yml
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual