services:
  gitea:
    image: gitea/gitea:1.20.0-rc2
    container_name: gitea
    restart: always
    ports:
      - 3022:22
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__actions__ENABLED=true
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=3000

    depends_on:
      - gitea_db

  gitea_db:
    image: postgres:alpine
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - gitea_db:/var/lib/postgresql/data

  gitea_runner:
    image: gitea/act_runner:nightly
    container_name: gitea_runner
    restart: always
    environment:
      CONFIG_FILE: /data/config.yaml
      GITEA_INSTANCE_URL: https://gitea.${DOMAIN}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${REGISTRATION_TOKEN}
    volumes:
      - gitea_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitea_data:
  gitea_db:
  gitea_runner:

networks:
  default:
    external: true
    name: ${DOCKER_NET}