services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    restart: always
    environment:
      - DOMAIN=https://vaultwarden.${DOMAIN}
      - DATABASE_URL=postgresql://vaultwarden:${DB_PASS}@vaultwarden_db:5432/vaultwarden
    volumes:
      - vaultwarden_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.service=vaultwarden
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80

    depends_on:
      - vaultwarden_db

  vaultwarden_db:
    image: postgres:alpine
    container_name: vaultwarden_db
    restart: always
    environment:
      - POSTGRES_USER=vaultwarden
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=vaultwarden
    volumes:
      - vaultwarden_db:/var/lib/postgresql/data

volumes:
  vaultwarden_data:
  vaultwarden_db:

networks:
  default:
    external: true
    name: ${DOCKER_NET}